apiVersion: v1
kind: Service
metadata:
  name: {{ include "bloom-vault.server.fullname" . }}
  labels:
    {{- include "bloom-vault.server.labels" . | nindent 4 }}
  #annotations:
  #  # Google Cloud Network Endpoint Groups (NEGs) for ingress
  #  cloud.google.com/neg: '{"ingress": true}'
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - name: {{ include "bloom-vault.server.fullname" . }}
      protocol: TCP
      port: {{ .Values.server.service.port }}
      targetPort: {{ .Values.server.service.targetPort }}

  selector:
    {{- include "bloom-vault.server.selectorLabels" . | nindent 4 }}
