apiVersion: v1
kind: Secret
metadata:
  annotations:
  name: bloom-vault-env-secret
type: Opaque
stringData:
  NODE_ENV: "production"
  PIPELINE_STAGE: "staging"
  TRUST_PROXY: "true"
  TOKEN_EXPIRATION_SECONDS: "86400"
  DISABLE_RATE_LIMITING: "true"
  ALLOW_ANONYMOUS: "true"
  
  LOG_URL: "https://logstash.bloom.co"
  LOG_USER: "actual-log-user"
  LOG_PASSWORD: "actual-log-password"
  
  POSTGRES_USER: "actual-postgres-user"
  POSTGRES_HOST: "postgres-host.bloom.internal"
  POSTGRES_PORT: "5432"
  POSTGRES_DATABASE: "vault-staging"
  POSTGRES_REQUIRE_SSL: "true"
  POSTGRES_PASSWORD: "actual-postgres-password"
