apiVersion: v1
stringData:
  .dockerconfigjson: |-
    {
    	"auths": {
    		"https://index.docker.io/v1/": {
    			"auth": "C0rnh0li0JYnBwJqOXFmaW5nMGo0NHaH5Zm7vbnJiaGZmU5d3Jnam1nZjBX0"
    		}
    	},
    	"HttpHeaders": {
    		"User-Agent": "Docker-Client/18.09.3-ce (linux)"
    	}
    } 
kind: Secret
metadata:
  annotations:
  name: myregistrykey
type: kubernetes.io/dockerconfigjson
